// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_Authorize_FullMethodName  = "/payment.v1.PaymentService/Authorize"
	PaymentService_Capture_FullMethodName    = "/payment.v1.PaymentService/Capture"
	PaymentService_Void_FullMethodName       = "/payment.v1.PaymentService/Void"
	PaymentService_Refund_FullMethodName     = "/payment.v1.PaymentService/Refund"
	PaymentService_GetPayment_FullMethodName = "/payment.v1.PaymentService/GetPayment"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentService is the internal (east-west) contract the order-fulfillment saga
// uses to move money: authorize a hold before reserving stock, capture it just
// before confirming the order, and void/refund as compensations. Browser traffic
// keeps using payment's REST surface; this gRPC surface is internal east-west
// (the saga's money operations, plus the read the order service uses to enrich
// order details with payment status).
//
// Every RPC is idempotent by the natural business key (order_id) — the saga needs
// no client-generated key, and a Temporal activity retry re-drives safely:
// re-authorizing an order returns its existing payment, and capture/void are
// no-ops once the payment is already in the target state.
type PaymentServiceClient interface {
	// Authorize places (or returns) the hold for an order. Idempotent by order_id
	// — one payment per order — so a retry returns the existing payment rather than
	// creating a second. A provider decline yields status = "failed" with a
	// decline_code (a normal response, not a gRPC error).
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	// Capture captures the authorized hold (money moves). Idempotent: capturing an
	// already-captured payment returns it unchanged.
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	// Void releases the authorized hold (compensation for Authorize). Idempotent:
	// voiding an already-voided payment succeeds.
	Void(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (*VoidResponse, error)
	// Refund returns captured money (compensation once captured). Idempotent by the
	// order (server key refund:{order_id}) — a retry returns the same refund.
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	// GetPayment returns the order's payment snapshot (read-only). The caller is
	// expected to have owner-scoped the order already — this internal surface
	// carries no end-user identity (NetworkPolicy is the fence). NOT_FOUND when
	// the order has no payment.
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, PaymentService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, PaymentService_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) Void(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (*VoidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoidResponse)
	err := c.cc.Invoke(ctx, PaymentService_Void_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, PaymentService_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// PaymentService is the internal (east-west) contract the order-fulfillment saga
// uses to move money: authorize a hold before reserving stock, capture it just
// before confirming the order, and void/refund as compensations. Browser traffic
// keeps using payment's REST surface; this gRPC surface is internal east-west
// (the saga's money operations, plus the read the order service uses to enrich
// order details with payment status).
//
// Every RPC is idempotent by the natural business key (order_id) — the saga needs
// no client-generated key, and a Temporal activity retry re-drives safely:
// re-authorizing an order returns its existing payment, and capture/void are
// no-ops once the payment is already in the target state.
type PaymentServiceServer interface {
	// Authorize places (or returns) the hold for an order. Idempotent by order_id
	// — one payment per order — so a retry returns the existing payment rather than
	// creating a second. A provider decline yields status = "failed" with a
	// decline_code (a normal response, not a gRPC error).
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	// Capture captures the authorized hold (money moves). Idempotent: capturing an
	// already-captured payment returns it unchanged.
	Capture(context.Context, *CaptureRequest) (*CaptureResponse, error)
	// Void releases the authorized hold (compensation for Authorize). Idempotent:
	// voiding an already-voided payment succeeds.
	Void(context.Context, *VoidRequest) (*VoidResponse, error)
	// Refund returns captured money (compensation once captured). Idempotent by the
	// order (server key refund:{order_id}) — a retry returns the same refund.
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	// GetPayment returns the order's payment snapshot (read-only). The caller is
	// expected to have owner-scoped the order already — this internal surface
	// carries no end-user identity (NetworkPolicy is the fence). NOT_FOUND when
	// the order has no payment.
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedPaymentServiceServer) Capture(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedPaymentServiceServer) Void(context.Context, *VoidRequest) (*VoidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Void not implemented")
}
func (UnimplementedPaymentServiceServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedPaymentServiceServer) GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_Void_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Void(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Void_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Void(ctx, req.(*VoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _PaymentService_Authorize_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _PaymentService_Capture_Handler,
		},
		{
			MethodName: "Void",
			Handler:    _PaymentService_Void_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _PaymentService_Refund_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentService_GetPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
