// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`      // minor units (cents); must match the order total
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                // ISO 4217; "USD" in v1 (mismatch → INVALID_ARGUMENT)
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // opaque token, never PAN-like data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AuthorizeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizeRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *AuthorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthorizeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type VoidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidRequest) Reset() {
	*x = VoidRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidRequest) ProtoMessage() {}

func (x *VoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidRequest.ProtoReflect.Descriptor instead.
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *VoidRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,2,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"` // amount to refund in minor units
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *RefundRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// Payment is the payment's post-operation snapshot, shared by the authorize/
// capture/void responses.
type Payment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PaymentId int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId   int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// pending | authorized | captured | voided | expired | failed | refunded.
	Status      string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AmountMinor int64  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency    string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Set only when status = "failed" (e.g. generic_decline, insufficient_funds).
	DeclineCode string `protobuf:"bytes,6,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	// Sum of applied refunds in minor units. A partial refund keeps status =
	// "captured" (refunded flips only when fully refunded), so callers rendering
	// payment state must derive "partially refunded" from this field.
	RefundedMinor int64 `protobuf:"varint,7,opt,name=refunded_minor,json=refundedMinor,proto3" json:"refunded_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *Payment) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetDeclineCode() string {
	if x != nil {
		return x.DeclineCode
	}
	return ""
}

func (x *Payment) GetRefundedMinor() int64 {
	if x != nil {
		return x.RefundedMinor
	}
	return 0
}

// Refund is a refund's post-operation snapshot.
type Refund struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RefundId  int64                  `protobuf:"varint,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PaymentId int64                  `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// pending | succeeded | failed.
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AmountMinor   int64  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *Refund) GetRefundId() int64 {
	if x != nil {
		return x.RefundId
	}
	return 0
}

func (x *Refund) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Refund) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizeResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type CaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *CaptureResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type VoidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidResponse) Reset() {
	*x = VoidResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidResponse) ProtoMessage() {}

func (x *VoidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidResponse.ProtoReflect.Descriptor instead.
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *VoidResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *RefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xac\x01\n" +
	"\x10AuthorizeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\"+\n" +
	"\x0eCaptureRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"(\n" +
	"\vVoidRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"e\n" +
	"\rRefundRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\famount_minor\x18\x02 \x01(\x03R\vamountMinor\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\".\n" +
	"\x11GetPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"\xe4\x01\n" +
	"\aPayment\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\fdecline_code\x18\x06 \x01(\tR\vdeclineCode\x12%\n" +
	"\x0erefunded_minor\x18\a \x01(\x03R\rrefundedMinor\"\x7f\n" +
	"\x06Refund\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\x03R\brefundId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\x03R\tpaymentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\"B\n" +
	"\x11AuthorizeResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment\"@\n" +
	"\x0fCaptureResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment\"=\n" +
	"\fVoidResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment\"<\n" +
	"\x0eRefundResponse\x12*\n" +
	"\x06refund\x18\x01 \x01(\v2\x12.payment.v1.RefundR\x06refund\"C\n" +
	"\x12GetPaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment2\xe7\x02\n" +
	"\x0ePaymentService\x12H\n" +
	"\tAuthorize\x12\x1c.payment.v1.AuthorizeRequest\x1a\x1d.payment.v1.AuthorizeResponse\x12B\n" +
	"\aCapture\x12\x1a.payment.v1.CaptureRequest\x1a\x1b.payment.v1.CaptureResponse\x129\n" +
	"\x04Void\x12\x17.payment.v1.VoidRequest\x1a\x18.payment.v1.VoidResponse\x12?\n" +
	"\x06Refund\x12\x19.payment.v1.RefundRequest\x1a\x1a.payment.v1.RefundResponse\x12K\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponseB\x9b\x01\n" +
	"\x0ecom.payment.v1B\fPaymentProtoP\x01Z2github.com/duynhlab/pkg/proto/payment/v1;paymentv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Payment.V1\xca\x02\n" +
	"Payment\\V1\xe2\x02\x16Payment\\V1\\GPBMetadata\xea\x02\vPayment::V1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payment_v1_payment_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),   // 0: payment.v1.AuthorizeRequest
	(*CaptureRequest)(nil),     // 1: payment.v1.CaptureRequest
	(*VoidRequest)(nil),        // 2: payment.v1.VoidRequest
	(*RefundRequest)(nil),      // 3: payment.v1.RefundRequest
	(*GetPaymentRequest)(nil),  // 4: payment.v1.GetPaymentRequest
	(*Payment)(nil),            // 5: payment.v1.Payment
	(*Refund)(nil),             // 6: payment.v1.Refund
	(*AuthorizeResponse)(nil),  // 7: payment.v1.AuthorizeResponse
	(*CaptureResponse)(nil),    // 8: payment.v1.CaptureResponse
	(*VoidResponse)(nil),       // 9: payment.v1.VoidResponse
	(*RefundResponse)(nil),     // 10: payment.v1.RefundResponse
	(*GetPaymentResponse)(nil), // 11: payment.v1.GetPaymentResponse
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	5,  // 0: payment.v1.AuthorizeResponse.payment:type_name -> payment.v1.Payment
	5,  // 1: payment.v1.CaptureResponse.payment:type_name -> payment.v1.Payment
	5,  // 2: payment.v1.VoidResponse.payment:type_name -> payment.v1.Payment
	6,  // 3: payment.v1.RefundResponse.refund:type_name -> payment.v1.Refund
	5,  // 4: payment.v1.GetPaymentResponse.payment:type_name -> payment.v1.Payment
	0,  // 5: payment.v1.PaymentService.Authorize:input_type -> payment.v1.AuthorizeRequest
	1,  // 6: payment.v1.PaymentService.Capture:input_type -> payment.v1.CaptureRequest
	2,  // 7: payment.v1.PaymentService.Void:input_type -> payment.v1.VoidRequest
	3,  // 8: payment.v1.PaymentService.Refund:input_type -> payment.v1.RefundRequest
	4,  // 9: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	7,  // 10: payment.v1.PaymentService.Authorize:output_type -> payment.v1.AuthorizeResponse
	8,  // 11: payment.v1.PaymentService.Capture:output_type -> payment.v1.CaptureResponse
	9,  // 12: payment.v1.PaymentService.Void:output_type -> payment.v1.VoidResponse
	10, // 13: payment.v1.PaymentService.Refund:output_type -> payment.v1.RefundResponse
	11, // 14: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.GetPaymentResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
