// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shipping/v1/shipping.proto

package shippingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShipmentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentByOrderRequest) Reset() {
	*x = GetShipmentByOrderRequest{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentByOrderRequest) ProtoMessage() {}

func (x *GetShipmentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *GetShipmentByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetShipmentByOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset when the order has no shipment yet.
	Shipment      *Shipment `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentByOrderResponse) Reset() {
	*x = GetShipmentByOrderResponse{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentByOrderResponse) ProtoMessage() {}

func (x *GetShipmentByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentByOrderResponse) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentByOrderResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type CreateShipmentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Free-form destination address carried from the order. The shipping service
	// generates the tracking number / carrier itself.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type CancelShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipmentRequest) Reset() {
	*x = CancelShipmentRequest{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipmentRequest) ProtoMessage() {}

func (x *CancelShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipmentRequest.ProtoReflect.Descriptor instead.
func (*CancelShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *CancelShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipmentResponse) Reset() {
	*x = CancelShipmentResponse{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipmentResponse) ProtoMessage() {}

func (x *CancelShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipmentResponse.ProtoReflect.Descriptor instead.
func (*CancelShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{5}
}

// Shipment mirrors the shipping service's JSON shipment shape 1:1 so the gRPC
// and HTTP paths produce identical aggregated responses. Timestamps are the
// service's preformatted RFC3339 strings (empty when unset) rather than
// google.protobuf.Timestamp, to avoid parse/format round-tripping that could
// change the wire value.
type Shipment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId           string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier           string                 `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	EstimatedDelivery string                 `protobuf:"bytes,6,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipping_v1_shipping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_shipping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipping_v1_shipping_proto_rawDescGZIP(), []int{6}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Shipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shipment) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

func (x *Shipment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Shipment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_shipping_v1_shipping_proto protoreflect.FileDescriptor

const file_shipping_v1_shipping_proto_rawDesc = "" +
	"\n" +
	"\x1ashipping/v1/shipping.proto\x12\vshipping.v1\"6\n" +
	"\x19GetShipmentByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"O\n" +
	"\x1aGetShipmentByOrderResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipping.v1.ShipmentR\bshipment\"L\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"K\n" +
	"\x16CreateShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipping.v1.ShipmentR\bshipment\"2\n" +
	"\x15CancelShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x18\n" +
	"\x16CancelShipmentResponse\"\xfd\x01\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x04 \x01(\tR\acarrier\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12-\n" +
	"\x12estimated_delivery\x18\x06 \x01(\tR\x11estimatedDelivery\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt2\xae\x02\n" +
	"\x0fShippingService\x12e\n" +
	"\x12GetShipmentByOrder\x12&.shipping.v1.GetShipmentByOrderRequest\x1a'.shipping.v1.GetShipmentByOrderResponse\x12Y\n" +
	"\x0eCreateShipment\x12\".shipping.v1.CreateShipmentRequest\x1a#.shipping.v1.CreateShipmentResponse\x12Y\n" +
	"\x0eCancelShipment\x12\".shipping.v1.CancelShipmentRequest\x1a#.shipping.v1.CancelShipmentResponseB\xa3\x01\n" +
	"\x0fcom.shipping.v1B\rShippingProtoP\x01Z4github.com/duynhlab/pkg/proto/shipping/v1;shippingv1\xa2\x02\x03SXX\xaa\x02\vShipping.V1\xca\x02\vShipping\\V1\xe2\x02\x17Shipping\\V1\\GPBMetadata\xea\x02\fShipping::V1b\x06proto3"

var (
	file_shipping_v1_shipping_proto_rawDescOnce sync.Once
	file_shipping_v1_shipping_proto_rawDescData []byte
)

func file_shipping_v1_shipping_proto_rawDescGZIP() []byte {
	file_shipping_v1_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_v1_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_v1_shipping_proto_rawDesc), len(file_shipping_v1_shipping_proto_rawDesc)))
	})
	return file_shipping_v1_shipping_proto_rawDescData
}

var file_shipping_v1_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shipping_v1_shipping_proto_goTypes = []any{
	(*GetShipmentByOrderRequest)(nil),  // 0: shipping.v1.GetShipmentByOrderRequest
	(*GetShipmentByOrderResponse)(nil), // 1: shipping.v1.GetShipmentByOrderResponse
	(*CreateShipmentRequest)(nil),      // 2: shipping.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),     // 3: shipping.v1.CreateShipmentResponse
	(*CancelShipmentRequest)(nil),      // 4: shipping.v1.CancelShipmentRequest
	(*CancelShipmentResponse)(nil),     // 5: shipping.v1.CancelShipmentResponse
	(*Shipment)(nil),                   // 6: shipping.v1.Shipment
}
var file_shipping_v1_shipping_proto_depIdxs = []int32{
	6, // 0: shipping.v1.GetShipmentByOrderResponse.shipment:type_name -> shipping.v1.Shipment
	6, // 1: shipping.v1.CreateShipmentResponse.shipment:type_name -> shipping.v1.Shipment
	0, // 2: shipping.v1.ShippingService.GetShipmentByOrder:input_type -> shipping.v1.GetShipmentByOrderRequest
	2, // 3: shipping.v1.ShippingService.CreateShipment:input_type -> shipping.v1.CreateShipmentRequest
	4, // 4: shipping.v1.ShippingService.CancelShipment:input_type -> shipping.v1.CancelShipmentRequest
	1, // 5: shipping.v1.ShippingService.GetShipmentByOrder:output_type -> shipping.v1.GetShipmentByOrderResponse
	3, // 6: shipping.v1.ShippingService.CreateShipment:output_type -> shipping.v1.CreateShipmentResponse
	5, // 7: shipping.v1.ShippingService.CancelShipment:output_type -> shipping.v1.CancelShipmentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shipping_v1_shipping_proto_init() }
func file_shipping_v1_shipping_proto_init() {
	if File_shipping_v1_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_v1_shipping_proto_rawDesc), len(file_shipping_v1_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_v1_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_v1_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_v1_shipping_proto_msgTypes,
	}.Build()
	File_shipping_v1_shipping_proto = out.File
	file_shipping_v1_shipping_proto_goTypes = nil
	file_shipping_v1_shipping_proto_depIdxs = nil
}
