// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shipping/v1/shipping.proto

package shippingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingService_GetShipmentByOrder_FullMethodName = "/shipping.v1.ShippingService/GetShipmentByOrder"
)

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShippingService is the internal (east-west) contract for the shipping
// service. It mirrors the existing HTTP route
//
//	GET /shipping/v1/internal/orders/{order_id}
//
// used by order-service for order-details aggregation. This is the gRPC
// Phase 1 pilot path (see homelab/docs/api/grpc-internal-comms.md).
type ShippingServiceClient interface {
	// GetShipmentByOrder returns the shipment for an order. The response
	// shipment is unset when no shipment exists for the order yet (the HTTP
	// route returns a null shipment in that case).
	GetShipmentByOrder(ctx context.Context, in *GetShipmentByOrderRequest, opts ...grpc.CallOption) (*GetShipmentByOrderResponse, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) GetShipmentByOrder(ctx context.Context, in *GetShipmentByOrderRequest, opts ...grpc.CallOption) (*GetShipmentByOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipmentByOrderResponse)
	err := c.cc.Invoke(ctx, ShippingService_GetShipmentByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
// All implementations must embed UnimplementedShippingServiceServer
// for forward compatibility.
//
// ShippingService is the internal (east-west) contract for the shipping
// service. It mirrors the existing HTTP route
//
//	GET /shipping/v1/internal/orders/{order_id}
//
// used by order-service for order-details aggregation. This is the gRPC
// Phase 1 pilot path (see homelab/docs/api/grpc-internal-comms.md).
type ShippingServiceServer interface {
	// GetShipmentByOrder returns the shipment for an order. The response
	// shipment is unset when no shipment exists for the order yet (the HTTP
	// route returns a null shipment in that case).
	GetShipmentByOrder(context.Context, *GetShipmentByOrderRequest) (*GetShipmentByOrderResponse, error)
	mustEmbedUnimplementedShippingServiceServer()
}

// UnimplementedShippingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingServiceServer struct{}

func (UnimplementedShippingServiceServer) GetShipmentByOrder(context.Context, *GetShipmentByOrderRequest) (*GetShipmentByOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShipmentByOrder not implemented")
}
func (UnimplementedShippingServiceServer) mustEmbedUnimplementedShippingServiceServer() {}
func (UnimplementedShippingServiceServer) testEmbeddedByValue()                         {}

// UnsafeShippingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingServiceServer will
// result in compilation errors.
type UnsafeShippingServiceServer interface {
	mustEmbedUnimplementedShippingServiceServer()
}

func RegisterShippingServiceServer(s grpc.ServiceRegistrar, srv ShippingServiceServer) {
	// If the following call panics, it indicates UnimplementedShippingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingService_ServiceDesc, srv)
}

func _ShippingService_GetShipmentByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentByOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetShipmentByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_GetShipmentByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetShipmentByOrder(ctx, req.(*GetShipmentByOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingService_ServiceDesc is the grpc.ServiceDesc for ShippingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipping.v1.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShipmentByOrder",
			Handler:    _ShippingService_GetShipmentByOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipping/v1/shipping.proto",
}
