// Code generated by weaver from semconv/ (the platform registry). DO NOT EDIT.
// Regenerate with `make semconv-generate`.

package temporalx

// Attribute keys temporalx writes, as the registry names them.
const (
	// How a Temporal run ended: failed, terminated or timed_out.
	KeyTemporalRunStatus = "temporal.run_status"
	// The Temporal task queue a started workflow was sent to.
	KeyTemporalTaskQueue = "temporal.task_queue"
	// The Temporal workflow type a lifecycle event names.
	KeyTemporalWorkflowType = "temporal.workflow.type"
)

// Workflow lifecycle event names temporalx owns.
const (
	// Emitted when: a run ends failed, terminated or timed out.
	EventTemporalWorkflowFailed = "temporal.workflow.failed"
	// Emitted when: the client starts a workflow.
	EventTemporalWorkflowStarted = "temporal.workflow.started"
)
