// Code generated by weaver from semconv/ (the platform registry). DO NOT EDIT.
// Regenerate with `make semconv-generate`.

package slogx

// Attribute keys the facade writes, as the registry names them.
const (
	// Which entry point a lifecycle event describes: api, worker or mockpay.
	KeyComponent = "component"
	// The catalog name of a named log event (docs/api/logs.md § Event catalog).
	KeyEvent = "event"
	// The bounded outcome of a decision, from the set the owning event or metric lists.
	KeyOutcome = "outcome"
)

// Lifecycle event names the facade owns.
const (
	// Emitted when: entry point ready to serve.
	EventProcessStarted = "process.started"
	// Emitted when: entry point finished shutting down.
	EventProcessStopped = "process.stopped"
)
