// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cart/v1/cart.proto

package cartv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id is the cart owner. gRPC carries no user JWT east-west: identity
	// crosses as an explicit field and NetworkPolicy is the fence — the same
	// accepted posture as ReserveStock/CreateShipment.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CartItem is one cart line. cart is the item-list authority (which products,
// what quantities); it is deliberately NOT the price authority.
type CartItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProductId   string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity    int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// cart_price_minor is cart's denormalized unit price in int64 minor units,
	// captured at add-to-cart time. Checkout compares it against product's
	// authoritative price to flag price-changed lines; it is never the price
	// charged (RFC-0015, homelab ADR-020).
	CartPriceMinor int64 `protobuf:"varint,4,opt,name=cart_price_minor,json=cartPriceMinor,proto3" json:"cart_price_minor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetCartPriceMinor() int64 {
	if x != nil {
		return x.CartPriceMinor
	}
	return 0
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_cart_v1_cart_proto protoreflect.FileDescriptor

const file_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x12cart/v1/cart.proto\x12\acart.v1\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x92\x01\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10cart_price_minor\x18\x04 \x01(\x03R\x0ecartPriceMinor\":\n" +
	"\x0fGetCartResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.cart.v1.CartItemR\x05items2K\n" +
	"\vCartService\x12<\n" +
	"\aGetCart\x12\x17.cart.v1.GetCartRequest\x1a\x18.cart.v1.GetCartResponseB\x83\x01\n" +
	"\vcom.cart.v1B\tCartProtoP\x01Z,github.com/duynhlab/pkg/proto/cart/v1;cartv1\xa2\x02\x03CXX\xaa\x02\aCart.V1\xca\x02\aCart\\V1\xe2\x02\x13Cart\\V1\\GPBMetadata\xea\x02\bCart::V1b\x06proto3"

var (
	file_cart_v1_cart_proto_rawDescOnce sync.Once
	file_cart_v1_cart_proto_rawDescData []byte
)

func file_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)))
	})
	return file_cart_v1_cart_proto_rawDescData
}

var file_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cart_v1_cart_proto_goTypes = []any{
	(*GetCartRequest)(nil),  // 0: cart.v1.GetCartRequest
	(*CartItem)(nil),        // 1: cart.v1.CartItem
	(*GetCartResponse)(nil), // 2: cart.v1.GetCartResponse
}
var file_cart_v1_cart_proto_depIdxs = []int32{
	1, // 0: cart.v1.GetCartResponse.items:type_name -> cart.v1.CartItem
	0, // 1: cart.v1.CartService.GetCart:input_type -> cart.v1.GetCartRequest
	2, // 2: cart.v1.CartService.GetCart:output_type -> cart.v1.GetCartResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_v1_cart_proto_init() }
func file_cart_v1_cart_proto_init() {
	if File_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_cart_v1_cart_proto = out.File
	file_cart_v1_cart_proto_goTypes = nil
	file_cart_v1_cart_proto_depIdxs = nil
}
