// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: product/v1/product.proto

package productv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_GetProducts_FullMethodName           = "/product.v1.ProductService/GetProducts"
	ProductService_BatchGetCurrentPrices_FullMethodName = "/product.v1.ProductService/BatchGetCurrentPrices"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductService is the internal (east-west) contract for the product service.
// It is a READ contract: price and catalog answers for checkout.
//
// The stock write operations it used to expose (ReserveStock / ReleaseStock) were
// REMOVED in RFC-0021 phase 4. Stock lives at inventory-service
// (inventory.v1.InventoryService), and no caller of these remained: the order
// saga's product branch was deleted in order 1.13.0 and checkout's availability
// read moved to inventory at W8. Field numbers are not reused — the messages go
// with the RPCs, so nothing can be silently rebound to a different meaning.
type ProductServiceClient interface {
	// GetProducts is a batch price/availability read used by checkout
	// re-validation (RFC-0015): product is the price authority at checkout
	// time. Read-only; the response omits unknown ids rather than erroring.
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	// BatchGetCurrentPrices is the price-only successor to GetProducts
	// (RFC-0021: availability moves to inventory.v1). DB-truth — it bypasses
	// the browsing cache like GetProducts does. Read-only; the response omits
	// unknown SKUs rather than erroring. GetProducts stays untouched until its
	// callers migrate (expand → migrate → contract).
	BatchGetCurrentPrices(ctx context.Context, in *BatchGetCurrentPricesRequest, opts ...grpc.CallOption) (*BatchGetCurrentPricesResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) BatchGetCurrentPrices(ctx context.Context, in *BatchGetCurrentPricesRequest, opts ...grpc.CallOption) (*BatchGetCurrentPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetCurrentPricesResponse)
	err := c.cc.Invoke(ctx, ProductService_BatchGetCurrentPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// ProductService is the internal (east-west) contract for the product service.
// It is a READ contract: price and catalog answers for checkout.
//
// The stock write operations it used to expose (ReserveStock / ReleaseStock) were
// REMOVED in RFC-0021 phase 4. Stock lives at inventory-service
// (inventory.v1.InventoryService), and no caller of these remained: the order
// saga's product branch was deleted in order 1.13.0 and checkout's availability
// read moved to inventory at W8. Field numbers are not reused — the messages go
// with the RPCs, so nothing can be silently rebound to a different meaning.
type ProductServiceServer interface {
	// GetProducts is a batch price/availability read used by checkout
	// re-validation (RFC-0015): product is the price authority at checkout
	// time. Read-only; the response omits unknown ids rather than erroring.
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	// BatchGetCurrentPrices is the price-only successor to GetProducts
	// (RFC-0021: availability moves to inventory.v1). DB-truth — it bypasses
	// the browsing cache like GetProducts does. Read-only; the response omits
	// unknown SKUs rather than erroring. GetProducts stays untouched until its
	// callers migrate (expand → migrate → contract).
	BatchGetCurrentPrices(context.Context, *BatchGetCurrentPricesRequest) (*BatchGetCurrentPricesResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedProductServiceServer) BatchGetCurrentPrices(context.Context, *BatchGetCurrentPricesRequest) (*BatchGetCurrentPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetCurrentPrices not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_BatchGetCurrentPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCurrentPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).BatchGetCurrentPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_BatchGetCurrentPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).BatchGetCurrentPrices(ctx, req.(*BatchGetCurrentPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "BatchGetCurrentPrices",
			Handler:    _ProductService_BatchGetCurrentPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/v1/product.proto",
}
