// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_BatchGetAvailability_FullMethodName = "/inventory.v1.InventoryService/BatchGetAvailability"
	InventoryService_CheckAvailability_FullMethodName    = "/inventory.v1.InventoryService/CheckAvailability"
	InventoryService_Reserve_FullMethodName              = "/inventory.v1.InventoryService/Reserve"
	InventoryService_Release_FullMethodName              = "/inventory.v1.InventoryService/Release"
	InventoryService_Commit_FullMethodName               = "/inventory.v1.InventoryService/Commit"
	InventoryService_GetReservation_FullMethodName       = "/inventory.v1.InventoryService/GetReservation"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService is the internal (east-west) contract for the inventory
// service — the sole authority for stock balances, reservations, and stock
// movements (RFC-0021, supersedes the product-owned stock surface in
// product.v1). Checkout calls the availability reads; the order-fulfillment
// saga calls Reserve/Release/Commit.
//
// Identity: sku_id is an opaque immutable string. In the initial migration
// one product is one sellable SKU (sku_id = product id); a future variant
// model adds SKUs without changing this contract.
//
// Errors carry a google.rpc.ErrorInfo detail with a stable reason
// (grpcx.ErrorWithReason): INSUFFICIENT_STOCK, SKU_NOT_FOUND,
// WAREHOUSE_NOT_FOUND, IDEMPOTENCY_CONFLICT, INVALID_TRANSITION,
// CONCURRENCY_CONFLICT, VALIDATION_ERROR, DEPENDENCY_UNAVAILABLE.
// Business reasons are non-retryable for workflow callers.
type InventoryServiceClient interface {
	// BatchGetAvailability returns per-SKU availability for product pages and
	// checkout snapshots. Read-only; unknown SKUs come back with status
	// AVAILABILITY_STATUS_UNKNOWN rather than erroring the batch.
	BatchGetAvailability(ctx context.Context, in *BatchGetAvailabilityRequest, opts ...grpc.CallOption) (*BatchGetAvailabilityResponse, error)
	// CheckAvailability answers "can this whole basket be fulfilled?" — the
	// checkout UX/revalidation gate. It is advisory only: the saga's Reserve is
	// the correctness gate (the check-then-reserve TOCTOU window cannot be
	// closed without holding a lock). Callers must not map a transport error
	// to "out of stock"; unavailability of inventory is retryable, absence of
	// stock is a business answer.
	CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error)
	// Reserve places an all-or-nothing hold on stock for an order (saga step).
	// Idempotent by reservation_id + request_hash: replaying the same request
	// returns the original result; the same reservation_id with a different
	// payload fails with IDEMPOTENCY_CONFLICT. The response reports the actual
	// warehouse allocation (one warehouse fulfills the whole order in v1).
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Release returns a reservation's stock (saga compensation, pre-pivot).
	// Idempotent: releasing an already-released reservation is a no-op success.
	// Releasing a COMMITTED reservation fails with INVALID_TRANSITION — a sale
	// is undone by a return movement, never by release.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// Commit converts a reservation into a sale (post-pivot mandatory forward:
	// on_hand and reserved both decrease, a SALE_COMMITTED movement is
	// recorded). Idempotent: committing a COMMITTED reservation returns it
	// unchanged. Committing a RELEASED reservation fails with
	// INVALID_TRANSITION. Callers retry this until it succeeds — a confirmed
	// order must converge to COMMITTED.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// GetReservation returns a reservation and its lines — used by the
	// order-domain reconciler and operators. Read-only.
	GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*GetReservationResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) BatchGetAvailability(ctx context.Context, in *BatchGetAvailabilityRequest, opts ...grpc.CallOption) (*BatchGetAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetAvailabilityResponse)
	err := c.cc.Invoke(ctx, InventoryService_BatchGetAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAvailabilityResponse)
	err := c.cc.Invoke(ctx, InventoryService_CheckAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, InventoryService_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, InventoryService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, InventoryService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetReservation(ctx context.Context, in *GetReservationRequest, opts ...grpc.CallOption) (*GetReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReservationResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// InventoryService is the internal (east-west) contract for the inventory
// service — the sole authority for stock balances, reservations, and stock
// movements (RFC-0021, supersedes the product-owned stock surface in
// product.v1). Checkout calls the availability reads; the order-fulfillment
// saga calls Reserve/Release/Commit.
//
// Identity: sku_id is an opaque immutable string. In the initial migration
// one product is one sellable SKU (sku_id = product id); a future variant
// model adds SKUs without changing this contract.
//
// Errors carry a google.rpc.ErrorInfo detail with a stable reason
// (grpcx.ErrorWithReason): INSUFFICIENT_STOCK, SKU_NOT_FOUND,
// WAREHOUSE_NOT_FOUND, IDEMPOTENCY_CONFLICT, INVALID_TRANSITION,
// CONCURRENCY_CONFLICT, VALIDATION_ERROR, DEPENDENCY_UNAVAILABLE.
// Business reasons are non-retryable for workflow callers.
type InventoryServiceServer interface {
	// BatchGetAvailability returns per-SKU availability for product pages and
	// checkout snapshots. Read-only; unknown SKUs come back with status
	// AVAILABILITY_STATUS_UNKNOWN rather than erroring the batch.
	BatchGetAvailability(context.Context, *BatchGetAvailabilityRequest) (*BatchGetAvailabilityResponse, error)
	// CheckAvailability answers "can this whole basket be fulfilled?" — the
	// checkout UX/revalidation gate. It is advisory only: the saga's Reserve is
	// the correctness gate (the check-then-reserve TOCTOU window cannot be
	// closed without holding a lock). Callers must not map a transport error
	// to "out of stock"; unavailability of inventory is retryable, absence of
	// stock is a business answer.
	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
	// Reserve places an all-or-nothing hold on stock for an order (saga step).
	// Idempotent by reservation_id + request_hash: replaying the same request
	// returns the original result; the same reservation_id with a different
	// payload fails with IDEMPOTENCY_CONFLICT. The response reports the actual
	// warehouse allocation (one warehouse fulfills the whole order in v1).
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Release returns a reservation's stock (saga compensation, pre-pivot).
	// Idempotent: releasing an already-released reservation is a no-op success.
	// Releasing a COMMITTED reservation fails with INVALID_TRANSITION — a sale
	// is undone by a return movement, never by release.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// Commit converts a reservation into a sale (post-pivot mandatory forward:
	// on_hand and reserved both decrease, a SALE_COMMITTED movement is
	// recorded). Idempotent: committing a COMMITTED reservation returns it
	// unchanged. Committing a RELEASED reservation fails with
	// INVALID_TRANSITION. Callers retry this until it succeeds — a confirmed
	// order must converge to COMMITTED.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// GetReservation returns a reservation and its lines — used by the
	// order-domain reconciler and operators. Read-only.
	GetReservation(context.Context, *GetReservationRequest) (*GetReservationResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) BatchGetAvailability(context.Context, *BatchGetAvailabilityRequest) (*BatchGetAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetAvailability not implemented")
}
func (UnimplementedInventoryServiceServer) CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedInventoryServiceServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedInventoryServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedInventoryServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedInventoryServiceServer) GetReservation(context.Context, *GetReservationRequest) (*GetReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReservation not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_BatchGetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BatchGetAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BatchGetAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BatchGetAvailability(ctx, req.(*BatchGetAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CheckAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CheckAvailability(ctx, req.(*CheckAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetReservation(ctx, req.(*GetReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchGetAvailability",
			Handler:    _InventoryService_BatchGetAvailability_Handler,
		},
		{
			MethodName: "CheckAvailability",
			Handler:    _InventoryService_CheckAvailability_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _InventoryService_Reserve_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _InventoryService_Release_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _InventoryService_Commit_Handler,
		},
		{
			MethodName: "GetReservation",
			Handler:    _InventoryService_GetReservation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
