// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvailabilityStatus classifies a SKU's availability without exposing exact
// quantities to surfaces that don't need them.
type AvailabilityStatus int32

const (
	AvailabilityStatus_AVAILABILITY_STATUS_UNSPECIFIED  AvailabilityStatus = 0
	AvailabilityStatus_AVAILABILITY_STATUS_IN_STOCK     AvailabilityStatus = 1
	AvailabilityStatus_AVAILABILITY_STATUS_LOW_STOCK    AvailabilityStatus = 2
	AvailabilityStatus_AVAILABILITY_STATUS_OUT_OF_STOCK AvailabilityStatus = 3
	// UNKNOWN means inventory could not answer (e.g. enrichment soft-fail).
	// It is never fabricated into OUT_OF_STOCK.
	AvailabilityStatus_AVAILABILITY_STATUS_UNKNOWN AvailabilityStatus = 4
)

// Enum value maps for AvailabilityStatus.
var (
	AvailabilityStatus_name = map[int32]string{
		0: "AVAILABILITY_STATUS_UNSPECIFIED",
		1: "AVAILABILITY_STATUS_IN_STOCK",
		2: "AVAILABILITY_STATUS_LOW_STOCK",
		3: "AVAILABILITY_STATUS_OUT_OF_STOCK",
		4: "AVAILABILITY_STATUS_UNKNOWN",
	}
	AvailabilityStatus_value = map[string]int32{
		"AVAILABILITY_STATUS_UNSPECIFIED":  0,
		"AVAILABILITY_STATUS_IN_STOCK":     1,
		"AVAILABILITY_STATUS_LOW_STOCK":    2,
		"AVAILABILITY_STATUS_OUT_OF_STOCK": 3,
		"AVAILABILITY_STATUS_UNKNOWN":      4,
	}
)

func (x AvailabilityStatus) Enum() *AvailabilityStatus {
	p := new(AvailabilityStatus)
	*p = x
	return p
}

func (x AvailabilityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (AvailabilityStatus) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x AvailabilityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilityStatus.Descriptor instead.
func (AvailabilityStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// ReservationStatus is the reservation FSM. RESERVED is the only non-terminal
// state; COMMITTED, RELEASED, and EXPIRED are terminal.
type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_RESERVED    ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_COMMITTED   ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_RELEASED    ReservationStatus = 3
	ReservationStatus_RESERVATION_STATUS_EXPIRED     ReservationStatus = 4
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_RESERVED",
		2: "RESERVATION_STATUS_COMMITTED",
		3: "RESERVATION_STATUS_RELEASED",
		4: "RESERVATION_STATUS_EXPIRED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_RESERVED":    1,
		"RESERVATION_STATUS_COMMITTED":   2,
		"RESERVATION_STATUS_RELEASED":    3,
		"RESERVATION_STATUS_EXPIRED":     4,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[1].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[1]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

// ReservationItem is a SKU/quantity pair requested for reservation.
type ReservationItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	SkuId string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	// Units requested; must be > 0.
	Quantity      int64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationItem) Reset() {
	*x = ReservationItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationItem) ProtoMessage() {}

func (x *ReservationItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationItem.ProtoReflect.Descriptor instead.
func (*ReservationItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReservationItem) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *ReservationItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Allocation reports where reserved stock is held. v1 allocates a whole
// reservation from one warehouse, so all allocations share warehouse_id.
type Allocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Allocation) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *Allocation) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *Allocation) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BatchGetAvailabilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SKUs to look up. Bounded batch; oversized requests fail VALIDATION_ERROR.
	SkuIds []string `protobuf:"bytes,1,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	// Optional destination region hint for warehouse filtering. Empty means
	// "any active warehouse".
	DestinationRegion string `protobuf:"bytes,2,opt,name=destination_region,json=destinationRegion,proto3" json:"destination_region,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchGetAvailabilityRequest) Reset() {
	*x = BatchGetAvailabilityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAvailabilityRequest) ProtoMessage() {}

func (x *BatchGetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*BatchGetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetAvailabilityRequest) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

func (x *BatchGetAvailabilityRequest) GetDestinationRegion() string {
	if x != nil {
		return x.DestinationRegion
	}
	return ""
}

type SkuAvailability struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SkuId  string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Status AvailabilityStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=inventory.v1.AvailabilityStatus" json:"status,omitempty"`
	// Units promisable right now (available_to_promise, floored at 0). Money
	// paths use this; browsing surfaces should prefer status.
	AvailableToPromise int64 `protobuf:"varint,3,opt,name=available_to_promise,json=availableToPromise,proto3" json:"available_to_promise,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SkuAvailability) Reset() {
	*x = SkuAvailability{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuAvailability) ProtoMessage() {}

func (x *SkuAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuAvailability.ProtoReflect.Descriptor instead.
func (*SkuAvailability) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SkuAvailability) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *SkuAvailability) GetStatus() AvailabilityStatus {
	if x != nil {
		return x.Status
	}
	return AvailabilityStatus_AVAILABILITY_STATUS_UNSPECIFIED
}

func (x *SkuAvailability) GetAvailableToPromise() int64 {
	if x != nil {
		return x.AvailableToPromise
	}
	return 0
}

type BatchGetAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Availabilities []*SkuAvailability     `protobuf:"bytes,1,rep,name=availabilities,proto3" json:"availabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchGetAvailabilityResponse) Reset() {
	*x = BatchGetAvailabilityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAvailabilityResponse) ProtoMessage() {}

func (x *BatchGetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*BatchGetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetAvailabilityResponse) GetAvailabilities() []*SkuAvailability {
	if x != nil {
		return x.Availabilities
	}
	return nil
}

type CheckAvailabilityRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Items             []*ReservationItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	DestinationRegion string                 `protobuf:"bytes,2,opt,name=destination_region,json=destinationRegion,proto3" json:"destination_region,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAvailabilityRequest) GetItems() []*ReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckAvailabilityRequest) GetDestinationRegion() string {
	if x != nil {
		return x.DestinationRegion
	}
	return ""
}

// Shortage names a line that cannot be fulfilled and by how much.
type Shortage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SkuId              string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Requested          int64                  `protobuf:"varint,2,opt,name=requested,proto3" json:"requested,omitempty"`
	AvailableToPromise int64                  `protobuf:"varint,3,opt,name=available_to_promise,json=availableToPromise,proto3" json:"available_to_promise,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Shortage) Reset() {
	*x = Shortage{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shortage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortage) ProtoMessage() {}

func (x *Shortage) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortage.ProtoReflect.Descriptor instead.
func (*Shortage) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *Shortage) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *Shortage) GetRequested() int64 {
	if x != nil {
		return x.Requested
	}
	return 0
}

func (x *Shortage) GetAvailableToPromise() int64 {
	if x != nil {
		return x.AvailableToPromise
	}
	return 0
}

type CheckAvailabilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when one warehouse can fulfill every line right now.
	CanFulfill bool `protobuf:"varint,1,opt,name=can_fulfill,json=canFulfill,proto3" json:"can_fulfill,omitempty"`
	// Empty when can_fulfill is true.
	Shortages     []*Shortage `protobuf:"bytes,2,rep,name=shortages,proto3" json:"shortages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *CheckAvailabilityResponse) GetCanFulfill() bool {
	if x != nil {
		return x.CanFulfill
	}
	return false
}

func (x *CheckAvailabilityResponse) GetShortages() []*Shortage {
	if x != nil {
		return x.Shortages
	}
	return nil
}

type ReserveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency key for the reservation — the order ID. At most one active
	// reservation exists per reservation_id.
	ReservationId string `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// The order this reservation fulfills (audit/reference; equals
	// reservation_id in the initial integration).
	OrderId           string             `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items             []*ReservationItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	DestinationRegion string             `protobuf:"bytes,4,opt,name=destination_region,json=destinationRegion,proto3" json:"destination_region,omitempty"`
	// Canonical hash of the business-effective request fields (items sorted by
	// sku_id, quantities, destination). A replay with the same reservation_id
	// and hash returns the original result; a different hash fails with
	// IDEMPOTENCY_CONFLICT.
	RequestHash string `protobuf:"bytes,5,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	// Optional observability-only expiry (RFC-3339). v1 never auto-expires an
	// active reservation; the reconciler reports reservations past this time.
	ExpiresAt     string `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveRequest) GetItems() []*ReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveRequest) GetDestinationRegion() string {
	if x != nil {
		return x.DestinationRegion
	}
	return ""
}

func (x *ReserveRequest) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *ReserveRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=inventory.v1.ReservationStatus" json:"status,omitempty"`
	// Actual allocation chosen (one warehouse in v1).
	Allocations   []*Allocation `protobuf:"bytes,3,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ReserveResponse) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	// Bounded reason code for the movement audit trail (e.g. the saga's
	// compensation cause). Free-form text is rejected server-side.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=inventory.v1.ReservationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CommitRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=inventory.v1.ReservationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *CommitResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *GetReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=inventory.v1.ReservationStatus" json:"status,omitempty"`
	Allocations   []*Allocation          `protobuf:"bytes,4,rep,name=allocations,proto3" json:"allocations,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *Reservation) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *Reservation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Reservation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Reservation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *GetReservationResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\"D\n" +
	"\x0fReservationItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"b\n" +
	"\n" +
	"Allocation\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"e\n" +
	"\x1bBatchGetAvailabilityRequest\x12\x17\n" +
	"\asku_ids\x18\x01 \x03(\tR\x06skuIds\x12-\n" +
	"\x12destination_region\x18\x02 \x01(\tR\x11destinationRegion\"\x94\x01\n" +
	"\x0fSkuAvailability\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .inventory.v1.AvailabilityStatusR\x06status\x120\n" +
	"\x14available_to_promise\x18\x03 \x01(\x03R\x12availableToPromise\"e\n" +
	"\x1cBatchGetAvailabilityResponse\x12E\n" +
	"\x0eavailabilities\x18\x01 \x03(\v2\x1d.inventory.v1.SkuAvailabilityR\x0eavailabilities\"~\n" +
	"\x18CheckAvailabilityRequest\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.inventory.v1.ReservationItemR\x05items\x12-\n" +
	"\x12destination_region\x18\x02 \x01(\tR\x11destinationRegion\"q\n" +
	"\bShortage\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x1c\n" +
	"\trequested\x18\x02 \x01(\x03R\trequested\x120\n" +
	"\x14available_to_promise\x18\x03 \x01(\x03R\x12availableToPromise\"r\n" +
	"\x19CheckAvailabilityResponse\x12\x1f\n" +
	"\vcan_fulfill\x18\x01 \x01(\bR\n" +
	"canFulfill\x124\n" +
	"\tshortages\x18\x02 \x03(\v2\x16.inventory.v1.ShortageR\tshortages\"\xf8\x01\n" +
	"\x0eReserveRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x123\n" +
	"\x05items\x18\x03 \x03(\v2\x1d.inventory.v1.ReservationItemR\x05items\x12-\n" +
	"\x12destination_region\x18\x04 \x01(\tR\x11destinationRegion\x12!\n" +
	"\frequest_hash\x18\x05 \x01(\tR\vrequestHash\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"\xad\x01\n" +
	"\x0fReserveResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.inventory.v1.ReservationStatusR\x06status\x12:\n" +
	"\vallocations\x18\x03 \x03(\v2\x18.inventory.v1.AllocationR\vallocations\"O\n" +
	"\x0eReleaseRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"q\n" +
	"\x0fReleaseResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.inventory.v1.ReservationStatusR\x06status\"6\n" +
	"\rCommitRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"p\n" +
	"\x0eCommitResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.inventory.v1.ReservationStatusR\x06status\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x8a\x02\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.inventory.v1.ReservationStatusR\x06status\x12:\n" +
	"\vallocations\x18\x04 \x03(\v2\x18.inventory.v1.AllocationR\vallocations\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"U\n" +
	"\x16GetReservationResponse\x12;\n" +
	"\vreservation\x18\x01 \x01(\v2\x19.inventory.v1.ReservationR\vreservation*\xc5\x01\n" +
	"\x12AvailabilityStatus\x12#\n" +
	"\x1fAVAILABILITY_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAVAILABILITY_STATUS_IN_STOCK\x10\x01\x12!\n" +
	"\x1dAVAILABILITY_STATUS_LOW_STOCK\x10\x02\x12$\n" +
	" AVAILABILITY_STATUS_OUT_OF_STOCK\x10\x03\x12\x1f\n" +
	"\x1bAVAILABILITY_STATUS_UNKNOWN\x10\x04*\xbb\x01\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RESERVED\x10\x01\x12 \n" +
	"\x1cRESERVATION_STATUS_COMMITTED\x10\x02\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RELEASED\x10\x03\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_EXPIRED\x10\x042\x99\x04\n" +
	"\x10InventoryService\x12m\n" +
	"\x14BatchGetAvailability\x12).inventory.v1.BatchGetAvailabilityRequest\x1a*.inventory.v1.BatchGetAvailabilityResponse\x12d\n" +
	"\x11CheckAvailability\x12&.inventory.v1.CheckAvailabilityRequest\x1a'.inventory.v1.CheckAvailabilityResponse\x12F\n" +
	"\aReserve\x12\x1c.inventory.v1.ReserveRequest\x1a\x1d.inventory.v1.ReserveResponse\x12F\n" +
	"\aRelease\x12\x1c.inventory.v1.ReleaseRequest\x1a\x1d.inventory.v1.ReleaseResponse\x12C\n" +
	"\x06Commit\x12\x1b.inventory.v1.CommitRequest\x1a\x1c.inventory.v1.CommitResponse\x12[\n" +
	"\x0eGetReservation\x12#.inventory.v1.GetReservationRequest\x1a$.inventory.v1.GetReservationResponseB\xab\x01\n" +
	"\x10com.inventory.v1B\x0eInventoryProtoP\x01Z6github.com/duynhlab/pkg/proto/inventory/v1;inventoryv1\xa2\x02\x03IXX\xaa\x02\fInventory.V1\xca\x02\fInventory\\V1\xe2\x02\x18Inventory\\V1\\GPBMetadata\xea\x02\rInventory::V1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(AvailabilityStatus)(0),              // 0: inventory.v1.AvailabilityStatus
	(ReservationStatus)(0),               // 1: inventory.v1.ReservationStatus
	(*ReservationItem)(nil),              // 2: inventory.v1.ReservationItem
	(*Allocation)(nil),                   // 3: inventory.v1.Allocation
	(*BatchGetAvailabilityRequest)(nil),  // 4: inventory.v1.BatchGetAvailabilityRequest
	(*SkuAvailability)(nil),              // 5: inventory.v1.SkuAvailability
	(*BatchGetAvailabilityResponse)(nil), // 6: inventory.v1.BatchGetAvailabilityResponse
	(*CheckAvailabilityRequest)(nil),     // 7: inventory.v1.CheckAvailabilityRequest
	(*Shortage)(nil),                     // 8: inventory.v1.Shortage
	(*CheckAvailabilityResponse)(nil),    // 9: inventory.v1.CheckAvailabilityResponse
	(*ReserveRequest)(nil),               // 10: inventory.v1.ReserveRequest
	(*ReserveResponse)(nil),              // 11: inventory.v1.ReserveResponse
	(*ReleaseRequest)(nil),               // 12: inventory.v1.ReleaseRequest
	(*ReleaseResponse)(nil),              // 13: inventory.v1.ReleaseResponse
	(*CommitRequest)(nil),                // 14: inventory.v1.CommitRequest
	(*CommitResponse)(nil),               // 15: inventory.v1.CommitResponse
	(*GetReservationRequest)(nil),        // 16: inventory.v1.GetReservationRequest
	(*Reservation)(nil),                  // 17: inventory.v1.Reservation
	(*GetReservationResponse)(nil),       // 18: inventory.v1.GetReservationResponse
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.SkuAvailability.status:type_name -> inventory.v1.AvailabilityStatus
	5,  // 1: inventory.v1.BatchGetAvailabilityResponse.availabilities:type_name -> inventory.v1.SkuAvailability
	2,  // 2: inventory.v1.CheckAvailabilityRequest.items:type_name -> inventory.v1.ReservationItem
	8,  // 3: inventory.v1.CheckAvailabilityResponse.shortages:type_name -> inventory.v1.Shortage
	2,  // 4: inventory.v1.ReserveRequest.items:type_name -> inventory.v1.ReservationItem
	1,  // 5: inventory.v1.ReserveResponse.status:type_name -> inventory.v1.ReservationStatus
	3,  // 6: inventory.v1.ReserveResponse.allocations:type_name -> inventory.v1.Allocation
	1,  // 7: inventory.v1.ReleaseResponse.status:type_name -> inventory.v1.ReservationStatus
	1,  // 8: inventory.v1.CommitResponse.status:type_name -> inventory.v1.ReservationStatus
	1,  // 9: inventory.v1.Reservation.status:type_name -> inventory.v1.ReservationStatus
	3,  // 10: inventory.v1.Reservation.allocations:type_name -> inventory.v1.Allocation
	17, // 11: inventory.v1.GetReservationResponse.reservation:type_name -> inventory.v1.Reservation
	4,  // 12: inventory.v1.InventoryService.BatchGetAvailability:input_type -> inventory.v1.BatchGetAvailabilityRequest
	7,  // 13: inventory.v1.InventoryService.CheckAvailability:input_type -> inventory.v1.CheckAvailabilityRequest
	10, // 14: inventory.v1.InventoryService.Reserve:input_type -> inventory.v1.ReserveRequest
	12, // 15: inventory.v1.InventoryService.Release:input_type -> inventory.v1.ReleaseRequest
	14, // 16: inventory.v1.InventoryService.Commit:input_type -> inventory.v1.CommitRequest
	16, // 17: inventory.v1.InventoryService.GetReservation:input_type -> inventory.v1.GetReservationRequest
	6,  // 18: inventory.v1.InventoryService.BatchGetAvailability:output_type -> inventory.v1.BatchGetAvailabilityResponse
	9,  // 19: inventory.v1.InventoryService.CheckAvailability:output_type -> inventory.v1.CheckAvailabilityResponse
	11, // 20: inventory.v1.InventoryService.Reserve:output_type -> inventory.v1.ReserveResponse
	13, // 21: inventory.v1.InventoryService.Release:output_type -> inventory.v1.ReleaseResponse
	15, // 22: inventory.v1.InventoryService.Commit:output_type -> inventory.v1.CommitResponse
	18, // 23: inventory.v1.InventoryService.GetReservation:output_type -> inventory.v1.GetReservationResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
